# kubernetes/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: creodamo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: creodamo
  template:
    metadata:
      labels:
        app: creodamo
    spec:
      containers:
      - name: creodamo
        image: creodamo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          runAsUser: 10000
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
