[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Jacque Antoine DeGraff<jacquedegraff@creodamo.com>"]

[tool.poetry.dependencies]
python = ">=3.12.1,<3.13"
azure-iot-starterkit-cli = "^1.1.0"
dynaconf = "^3.2.4"

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
# https://beta.ruff.rs/docs/configuration/
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
