[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Jacque Antoine DeGraff<jacquedegraff@creodamo.com>"]

[tool.poetry.dependencies]
python = ">=3.12.1,<3.13"
azure-iot-starterkit-cli = "^1.1.0"
dynaconf = "^3.2.4"
pandas = "2.1.4"
numpy = "1.26.2"
Django = "5.0"
scikit-learn = "1.3.2"
pytest = "*"
pytest-mock = "*"
coverage = "*"
Sphinx = "*"
mkdocs = "*"
pycco = "*"
django-stubs = "*"
typing-extensions = "*"
python-dotenv = "*"
django-rest-framework = "*"
djangorestframework-simplejwt = "*"
djangorestframework-camel-case = "*"
django-cors-headers = "*"
django-auth-ldap = "*"
django-oauth-toolkit = "*"
gunicorn = "*"
whitenoise = "*"
psycopg2-binary = "*"
aiohttp = ">=3.9.0"

[tool.poetry.scripts]
creodamo = "run:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
